// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhY6xVjgA3DyHq5WVJU6vTPmulAP0NaPU',
    appId: '1:746895043083:web:3791953ef32bee7270350e',
    messagingSenderId: '746895043083',
    projectId: 'spshelper-3e8c8',
    authDomain: 'spshelper-3e8c8.firebaseapp.com',
    storageBucket: 'spshelper-3e8c8.firebasestorage.app',
    measurementId: 'G-9TR8V2HFDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCamTJRDL7GdCYsEhyJpFg0hyS49jc-RmI',
    appId: '1:746895043083:android:4718651433249f8470350e',
    messagingSenderId: '746895043083',
    projectId: 'spshelper-3e8c8',
    storageBucket: 'spshelper-3e8c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFIbGaeE4J61SO4RJ8enfdLsQ4GZUNrho',
    appId: '1:746895043083:ios:2ea7baf0b39039d770350e',
    messagingSenderId: '746895043083',
    projectId: 'spshelper-3e8c8',
    storageBucket: 'spshelper-3e8c8.firebasestorage.app',
    iosBundleId: 'com.example.spsHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFIbGaeE4J61SO4RJ8enfdLsQ4GZUNrho',
    appId: '1:746895043083:ios:2ea7baf0b39039d770350e',
    messagingSenderId: '746895043083',
    projectId: 'spshelper-3e8c8',
    storageBucket: 'spshelper-3e8c8.firebasestorage.app',
    iosBundleId: 'com.example.spsHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhY6xVjgA3DyHq5WVJU6vTPmulAP0NaPU',
    appId: '1:746895043083:web:6b6b18a5d4f84f3170350e',
    messagingSenderId: '746895043083',
    projectId: 'spshelper-3e8c8',
    authDomain: 'spshelper-3e8c8.firebaseapp.com',
    storageBucket: 'spshelper-3e8c8.firebasestorage.app',
    measurementId: 'G-WKRWP82CP4',
  );
}
